/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pony_cartoon.glb -o src/components/models/PonyCartoon.jsx
Author: Slava Z. (https://sketchfab.com/slava)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pony-cartoon-885d9f60b3a9429bb4077cfac5653cf9
Title: Pony Cartoon
*/

import {
  forwardRef,
  useImperativeHandle,
  useLayoutEffect,
  useRef,
} from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { Basename, TARGET_HEIGHT } from "../../constants";

const modelUrl = Basename + "/models/pony_cartoon.glb";

const PonyCartoonModel = forwardRef(function PonyCartoonModel(props, ref) {
  const groupRef = useRef(null);
  useImperativeHandle(ref, () => groupRef.current);
  const { nodes, materials } = useGLTF(modelUrl);

  useLayoutEffect(() => {
    if (!groupRef.current) return;

    const box = new THREE.Box3().setFromObject(groupRef.current);
    const size = box.getSize(new THREE.Vector3());
    const maxDim = Math.max(size.x, size.y, size.z);

    if (maxDim <= 0) return;

    const suggestedScale = TARGET_HEIGHT / maxDim;
    groupRef.current.scale.setScalar(suggestedScale);
    console.log(
      "[PonyCartoonModel] bounding box size:",
      size,
      "suggested scale:",
      suggestedScale,
    );
  }, []);

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.004}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Body_SG1}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Ground_SG}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Interior_SG}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Windows_SG}
        />
      </group>
    </group>
  );
});

useGLTF.preload(modelUrl);

export default PonyCartoonModel;
