/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/skritek_-_wooden_statue.glb -o src/components/models/skritek-wooden-statue.jsx 
Author: 3dhdscan (https://sketchfab.com/3dhdscan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skritek-wooden-statue-ad0c5e3cd1c542159138a861b1146f67
Title: Skřítek - wooden statue
*/

import { forwardRef, useLayoutEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { Basename } from '../../constants'
import * as THREE from 'three'

const modelUrl = Basename + '/models/skritek_-_wooden_statue.glb'
const TARGET_HEIGHT = 2 // normalize model to ~2 units tall

const Model = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF(modelUrl)

  useLayoutEffect(() => {
    if (!ref?.current) return
    ref.current.scale.set(1, 1, 1)
    const box = new THREE.Box3().setFromObject(ref.current)
    const size = box.getSize(new THREE.Vector3())
    const maxDim = Math.max(size.x, size.y, size.z)
    const s = TARGET_HEIGHT / maxDim
    ref.current.scale.setScalar(s)
    console.log(
      '[skritek-wooden-statue] normalized scale:',
      s,
      '| size at scale=1:',
      size,
    )
  }, [])

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.prigl_skritek_prigl_skritekDiffuseMap_0.geometry}
        material={materials.prigl_skritekDiffuseMap}
        position={[-0.364, 0.057, -0.107]}
        rotation={[-Math.PI, -Math.PI / 6, 0]}
      />
    </group>
  )
})
useGLTF.preload(modelUrl)

export default Model
