/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/armor.glb -o src/components/models/the-knights-armor.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { Basename } from '../../constants'
import { forwardRef } from 'react'
const modelUrl = Basename + '/models/armor.glb'

const Model = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF(modelUrl)

  materials.material_0.depthWrite = true
  // materials.material_0.metalness = 0
  materials.material_0.transparent = true
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        castShadow
        receiveShadow
        geometry={nodes.armor.geometry}
        material={materials.material_0}
        position={[0, 0.162, 0]}
      />
    </group>
  )
})

useGLTF.preload(modelUrl)

export default Model
